#!/usr/bin/env bash
# Installs and configures nginx

apt -y update
apt -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
service nginx start
