#!/usr/bin/env bash
# This script creates a file containing its PID and plays with signals
echo "$$" > /var/run/holbertonscript.pid
trap "echo 'I hate the kill command'; rm /var/run/holbertonscript.pid; exit 0" TERM
trap "echo 'Y U no love me?!'" INT
trap "rm /var/run/holbertonscript.pid; exit 0" QUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done