#!/usr/bin/env bash
# This script displays "To infinity and beyond" every 2 seconds forever, and mocks the user for trying to terminate its process
while true; do
    echo "To infinity and beyond"
    trap "echo 'I am invincible!!!'" TERM
    sleep 2
done