#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times, except for the 9th iteration
i=1
while [ $i -le 10 ]; do
	if [ $i -eq 9 ]; then
		echo "Hi"
	else
		echo "Holberton School"
	fi
	((i++))
done
exit 0
