#!/usr/bin/env bash
# This script displays every minute of every hour of a day
hr=0
while [ $hr -le 12 ]; do
	echo "Hour: $hr"
    min=0
    while [ $min -lt 60 ]; do
        echo $min
        ((min++))
    done
    ((hr++))
done
exit 0
