#!/usr/bin/env bash
# This script gives information about the holbertonschool
file="holbertonschool"
if test -e $file; then
	echo "$file file exists"

	if test -s $file; then
		echo "$file file is not empty"
	else
		echo "$file file is empty"
	fi

	if test -f $file; then
		echo "$file file is a regular file"
	fi
else
	echo "$file file does not exist"
fi

exit 0
