#!/usr/bin/env bash
# Install & configure ufw to deny everything except ssh, http and https

apt install ufw -y
ufw default deny incoming
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
ufw enable