#!/usr/bin/env bash
# Run nginx as nginx
pkill -f apache2
sed -i s/80/8080/g /etc/nginx/sites-available/default
# sudo chown -R nginx:nginx /etc/nginx/nginx.conf
sudo chmod -R 700 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
